# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a74d10812f6b20f1670be01aa3150d128330573f4a4b1c1a97be5c105a8781def030d8339df4115dccba8d9be276c76129b6fe30d1660b8d6532c4c98bf6c2c

test:
  secret_key_base: a3e0f7920b08ce9bb264c193c5dd254ba54c80ce3c4083ff372fa32e77d2508d19a4b8d3d2bbca139bdc8a5ba8ea4c4d29033b651ef2bae624e0baf8a367dded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
