# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 920666f7f02c7dc5e436dafb237e7d1fc8e65bfcbd448cf5b8b46f49a5173b23c03ce59592de6353a7a4e5aef0c9b505fd039a15b6b033f6b58d05f8b9a36997

test:
  secret_key_base: 54e1bb5999291bb1c1245daedcd17e73c48e9e5c4653a1d39ff075cd7f54cdb1ae0b9d4a17dd28b6994f5dda904386d5bdbb0ffee32a7b4507235dac01ebac28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
